### ISSUE TITLE
Issue: Проблема при send message и threads

### ISSUE THREAD

**Issue by Xemach** [chat2desk/ios-sdk-demo#6]
Здравствуйте, я столкнулся с проблемой при отправке сообщения из-за не соответствия потоков в Realm. 
Первая проблема с которой я столкнулся, была при отсутствии исполнения в главном потоке. 

`Terminating app due to uncaught exception 'NSGenericException', reason: 'Calling Kotlin suspend functions from Swift/Objective-C is currently supported only on main thread`

При добавлении @MainActor или DispatchQueue.main.async. При отправке возникает ошибка связанная с Realm (скрин: 2).
Может быть, вы знаете решение?

<img width="1226" alt="error_trace" src="https://github.com/chat2desk/ios-sdk-demo/assets/67548432/b4f931f4-bf8f-4c43-9053-557ce9000ba5">

![Снимок экрана 2023-11-15 в 17 45 43](https://github.com/chat2desk/ios-sdk-demo/assets/67548432/c6bd5bf7-cf21-44ef-ba40-f4e592e78428)

**Comment by xIscateLx** [comment]
попробуйте через:

`Task {
            try await chat2desk.sendMessage(msg: text)
        }`
